package com.api.spring.security.util;

public enum RolePermision {
    READ_ALL_PRODUCTS,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DISABLED_ONE_PRODUCT,

    READ_ALL_CATEGORIES,
    READ_ONE_CATEGORY,
    CREATE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DISABLED_ONE_CATEGORY,

    READ_MY_PROFILE;
}
